<?php

namespace ContainerQGxdJTq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateGenerPostControllerService extends RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer
{
    /**
     * Gets the public 'RaspinuOffice\Apps\Backoffice\Controller\Gener\CreateGenerPostController' shared autowired service.
     *
     * @return \RaspinuOffice\Apps\Backoffice\Controller\Gener\CreateGenerPostController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Gener/CreateGenerPostController.php';

        return $container->services['RaspinuOffice\\Apps\\Backoffice\\Controller\\Gener\\CreateGenerPostController'] = new \RaspinuOffice\Apps\Backoffice\Controller\Gener\CreateGenerPostController();
    }
}
