<?php

namespace ContainerQGxdJTq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer
{
    /**
     * Gets the public 'RaspinuOffice\Apps\Backoffice\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \RaspinuOffice\Apps\Backoffice\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['RaspinuOffice\\Apps\\Backoffice\\Controller\\HealthCheck\\HealthCheckGetController'] = new \RaspinuOffice\Apps\Backoffice\Controller\HealthCheck\HealthCheckGetController();
    }
}
