<?php

namespace ContainerLZuxfBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_TranslationDebugService extends RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer
{
    /**
     * Gets the private 'console.command.translation_debug' shared service.
     *
     * @return \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php';

        $container->privates['console.command.translation_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand(($container->services['translator'] ?? $container->load('getTranslatorService')), ($container->privates['translation.reader'] ?? $container->load('getTranslation_ReaderService')), ($container->privates['translation.extractor'] ?? $container->load('getTranslation_ExtractorService')), (\dirname(__DIR__, 4).'/translations'), NULL, [0 => (\dirname(__DIR__, 6).'/vendor/symfony/validator/Resources/translations'), 1 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Resources/translations'), 2 => (\dirname(__DIR__, 6).'/vendor/symfony/security-core/Resources/translations')], [0 => (\dirname(__DIR__, 6).'/vendor/symfony/http-kernel/EventListener/LocaleAwareListener.php'), 1 => (\dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php'), 2 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Core/Type/ChoiceType.php'), 3 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Core/Type/ColorType.php'), 4 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Core/Type/TransformationFailureExtension.php'), 5 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Validator/Type/FormTypeValidatorExtension.php'), 6 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Validator/Type/UploadValidatorExtension.php'), 7 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php'), 8 => (\dirname(__DIR__, 6).'/vendor/symfony/validator/ValidatorBuilder.php'), 9 => (\dirname(__DIR__, 6).'/vendor/symfony/framework-bundle/CacheWarmer/TranslationsCacheWarmer.php'), 10 => (\dirname(__DIR__, 6).'/vendor/symfony/form/Extension/Core/Type/FileType.php')]);

        $instance->setName('debug:translation');

        return $instance;
    }
}
