<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQGxdJTq\RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQGxdJTq/RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQGxdJTq.legacy');

    return;
}

if (!\class_exists(RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQGxdJTq\RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer::class, RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer::class, false);
}

return new \ContainerQGxdJTq\RaspinuOffice_Apps_Backoffice_BackofficeKernelDevDebugContainer([
    'container.build_hash' => 'QGxdJTq',
    'container.build_id' => '9ae1844e',
    'container.build_time' => 1621954457,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQGxdJTq');
