<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'health-check_get' => [[], ['_controller' => 'RaspinuOffice\\Apps\\Backoffice\\Controller\\HealthCheck\\HealthCheckGetController'], [], [['text', '/health-check']], [], []],
];
